name: Check for compilation and test failures

on:
  push:
    branches:
      - master

jobs:
  compile-check-and-test:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Install dependencies
        run: |
          pacman -Suy --noconfirm --needed \
            base-devel \
            git \
            meson \
            clang \
            boost \
            icu

      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Compile
        run: |
          mkdir build && cd build
          meson setup -D build_testing=true
          meson compile

      - name: Check clang-tidy
        run: ninja clang-tidy

      - name: Run tests
        run: meson test --print-errorlogs
